### ISSUE TITLE
Edge widens the dialog to fit the title

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/Office-Add-in-Dialog-API-Simple-Example#11]
When opening a dialog, and specifying the width and height, Edge seems to ignore the width, and widen the dialog, in order to fit the title (which includes the url, which is in itself already not desirable)
This causes an ugly dialog to be displayed for us.

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
