### ISSUE TITLE
There is no maximize button to make the dialog full screen

### ISSUE THREAD

**Issue by webdroidco** [OfficeDev/Office-Add-in-Dialog-API-Simple-Example#4]
I really like this dialog but I would really appreciate if someone adds maximize button to make the dialog full screen. And if it is full size then minimize the dialog to its original size. 

Is it possible?

**Comment by mikewheaton** [comment]
@Rick-Kirkham, @LezaMax: I've searched through this repository and don't see where `ms-Dialog` is used to create a Dialog component.Do you know where the Dialog is created? There's no built-in support for maximizing a Dialog to full screen, but I may be able to point @webdroidco in the right direction to overriding the CSS to achieve this.

**Comment by webdroidco** [comment]
Yes, exactly. I wasn't able to see any code with which the dialog is created.
Should I wait now for @Rick-Kirkham  and @LezaMax  so that they can tell you where exactly the code is?

**Comment by Rick-Kirkham** [comment]
@webdroidco 
The dialog is created with the line  `Office.context.ui.displayDialogAsync( ... )` in the file DialogHelper.js. You can set the width and height with the options parameter to that function. (The values are percentages of the screen.)
`ms-Dialog `is a Fabric thing that is not related to the Dialog APIs which this sample is about. I recommend that you read [Dialog API in Office Add-ins](https://dev.office.com/docs/add-ins/develop/dialog-api-in-office-add-ins)

**Comment by webdroidco** [comment]
@Rick-Kirkham Well, I am a newbie in Add-ins so that is why I am not able to follow your instructions properly. But please let me know if there is anyway (ANY) that we can add maximize button beside close button to make the dialog full screen (100% of the screen)?

**Comment by Rick-Kirkham** [comment]
There isn't a way to do that with the Dialog APIs. I'm not familiar with the Fabric dialog component, so I don't know if there's a way to do it with that component.

**Comment by webdroidco** [comment]
@Rick-Kirkham 
Is it possible to play Youtube or Vimeo video in this dialog and when clicking on the full-screen button, the screen becomes full size?

**Comment by Rick-Kirkham** [comment]
I don't think so, but there is a sample here: https://github.com/OfficeDev/Office-Add-in-UX-Design-Patterns-Code/tree/master/templates/first-run/video-placemat which opens a video in a dialog. You could run it and see what happens with the full screen button.

**Comment by webdroidco** [comment]
Nothing happen with the full screen button. The dialog size remains the same. :(

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
