### ISSUE TITLE
Does the Dialog API supports Outlook WebClient( OWA)

### ISSUE THREAD

**Issue by AhmedVali** [OfficeDev/Office-Add-in-Dialog-API-Simple-Example#5]
Hi ,

Is the Dailaog API 1.1 available for OWA ?

When I tried to do so, I m getting the 5001 Internal Error
osfruntime.js:13 Error while parsing the 'sandbox' attribute: ms-allow-popups

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
