### ISSUE TITLE
ScriptedSandbox64.exe has stopped working

### ISSUE THREAD

**Issue by Namiqismayil** [OfficeDev/Office-Add-in-Dialog-API-Simple-Example#7]
Hi,

I am getting this message after 2 seconds I click 'pick a number' on Word .

![image](https://user-images.githubusercontent.com/15338001/36316737-1e5e3eb2-1309-11e8-8fa5-203e43599183.png)

*Using Visual studio 2017

Any idea how to fix it?

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
