### ISSUE TITLE
The Office Js Dialog API contains a bug where the width and the height are swapped

### ISSUE THREAD

**Issue by hg3317593** [OfficeDev/Office-Add-in-Dialog-API-Simple-Example#8]
The Office Js Dialog API contains a bug where the width and the height are swapped when using "Office.context.ui.displayDialogAsync". This bug occurs in the latest version of all desktop apps (Word/Excel/PowerPoint). Not in Office Online. Is this bug known?
When I set width: 100, it shows the height is 100%.
![a1](https://user-images.githubusercontent.com/31742075/43421982-eab167f8-947a-11e8-8ebb-b89ad3c2a0fa.png)
![a2](https://user-images.githubusercontent.com/31742075/43421984-ee4d87d4-947a-11e8-9714-96e0a48be7a3.png)

Is it a known issue and when it will be fixed?

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
