### ISSUE TITLE
Office.context.ui.messageParent can't talk back to the host in Outlook Online (Web)

### ISSUE THREAD

**Issue by zipboy** [OfficeDev/Office-Add-in-Dialog-API-Simple-Example#9]
I am trying to build outlook plugin and I put it and test it on Outlook online, however, "**Office.context.ui.messageParent**" can't talk back to the host.

in host page, it run below code for user to login (I use AzureAD SSO for login user)
```
var fullUrl = location.protocol + '//' + location.hostname + (location.port ? ':' + location.port : '') + "/AzureAD/Login";
        Office.context.ui.displayDialogAsync(fullUrl, {
            height: 60,
            width: 60,
        }, function (result) {
            var dialog = result.value;
            dialog.addEventHandler(Microsoft.Office.WebExtension.EventType.DialogMessageReceived, processMessage);
        });

function processMessage(arg) {
        var resp = JSON.parse(arg.message);
        console.log("Message received: " + JSON.stringify(resp));

}
```

it shows the dialog with AzureAD permission correctly, user give the consent, after that, this dialog suppose to talk back to the host by using below code (in dialog):

```
Office.initialize = function (reason) {
            $(document).ready(function () {             
                    Office.context.ui.messageParent(true);                
                });
        };
```

However, the host can't get any message in processMessage function.

### But, the same code works fine for my Word Add-in for Word Online.

I also checked DialogAPI doc, (https://docs.microsoft.com/zh-cn/javascript/api/office/office.ui?product=outlook&view=office-js#displaydialogasync-startaddress--options--callback-)

It mentioned: "**This method is available in the DialogApi requirement set for Word, Excel, or PowerPoint add-ins, and in the Mailbox requirement set 1.4 for Outlook**".

And I did put 1.6 in my manifest file.

```
<Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.6" />
    </Sets>
  </Requirements>
```

Still no luck, any idea?

Thanks

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
